variable "stack_id" {
  description = "Unique stack identifier, auto-generated by tf wrapper"
  type        = string
}

variable "aws_region" {
  description = "AWS region"
  type        = string
  default     = "us-east-1"
}

variable "project_name" {
  description = "Project name used for resource naming"
  type        = string
  default     = "parmail"
}

variable "parent_domain" {
  description = "Parent domain you own (must have a Route53 hosted zone). Subdomain parmail.<domain> will be created."
  type        = string
  default     = ""

  validation {
    condition     = var.parent_domain != ""
    error_message = "parent_domain is required. Set TF_VAR_parent_domain env var or pass -var=\"parent_domain=example.com\""
  }
}

variable "email_user" {
  description = "Local part of the email address (e.g. 'usps' becomes usps@parmail.<domain>)"
  type        = string
  default     = "usps"
}

variable "force_destroy_bucket" {
  description = "Allow terraform destroy to delete the S3 bucket even if it contains objects"
  type        = bool
  default     = false
}

variable "force_delete_ecr" {
  description = "Allow terraform destroy to delete ECR repositories even if they contain images"
  type        = bool
  default     = false
}

